import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "./generated/client/client";

const connectionString = process.env.DATABASE_URL ?? "postgresql://postgres:postgres@localhost:5432/demo_project";
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const SEED_FOODS = [
  // PROTEIN SOURCES
  {
    name: "Chicken breast (grilled)",
    category: "Protein - Meat",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: "100g",
  },
  {
    name: "Chicken thigh (grilled)",
    category: "Protein - Meat",
    calories: 177,
    protein: 24,
    carbs: 0,
    fat: 8.5,
    servingSize: "100g",
  },
  {
    name: "Lean beef (sirloin, cooked)",
    category: "Protein - Meat",
    calories: 170,
    protein: 26,
    carbs: 0,
    fat: 7,
    servingSize: "100g",
  },
  {
    name: "Ground beef (85% lean, cooked)",
    category: "Protein - Meat",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 17,
    servingSize: "100g",
  },
  {
    name: "Salmon (cooked)",
    category: "Protein - Fish",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    servingSize: "100g",
  },
  {
    name: "Tuna (canned in water)",
    category: "Protein - Fish",
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 0.8,
    servingSize: "100g",
  },
  {
    name: "White fish (cod, cooked)",
    category: "Protein - Fish",
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    servingSize: "100g",
  },
  {
    name: "Whole egg (large)",
    category: "Protein - Egg",
    calories: 70,
    protein: 6,
    carbs: 0.5,
    fat: 5,
    servingSize: "1 large (50g)",
  },
  {
    name: "Egg white",
    category: "Protein - Egg",
    calories: 17,
    protein: 3.6,
    carbs: 0,
    fat: 0,
    servingSize: "1 large",
  },
  {
    name: "Greek yogurt (non-fat)",
    category: "Protein - Dairy",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    servingSize: "100g",
  },
  {
    name: "Greek yogurt (full fat)",
    category: "Protein - Dairy",
    calories: 97,
    protein: 9,
    carbs: 3.6,
    fat: 5,
    servingSize: "100g",
  },
  {
    name: "Cottage cheese (low fat)",
    category: "Protein - Dairy",
    calories: 72,
    protein: 11,
    carbs: 3.4,
    fat: 1.5,
    servingSize: "100g",
  },
  {
    name: "Whey protein powder",
    category: "Protein - Supplement",
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
    servingSize: "30g scoop",
  },
  {
    name: "Tofu (firm)",
    category: "Protein - Plant",
    calories: 144,
    protein: 17,
    carbs: 3,
    fat: 9,
    servingSize: "100g",
  },
  {
    name: "Tempeh",
    category: "Protein - Plant",
    calories: 193,
    protein: 19,
    carbs: 9,
    fat: 11,
    servingSize: "100g",
  },
  // CARBS
  {
    name: "White rice (cooked)",
    category: "Carbs - Grains",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    servingSize: "100g",
  },
  {
    name: "Brown rice (cooked)",
    category: "Carbs - Grains",
    calories: 123,
    protein: 2.7,
    carbs: 25,
    fat: 1,
    servingSize: "100g",
  },
  {
    name: "Jasmine rice (cooked)",
    category: "Carbs - Grains",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    servingSize: "100g",
  },
  {
    name: "Quinoa (cooked)",
    category: "Carbs - Grains",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    servingSize: "100g",
  },
  {
    name: "Oats (dry)",
    category: "Carbs - Grains",
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    servingSize: "100g",
  },
  {
    name: "Oatmeal (cooked)",
    category: "Carbs - Grains",
    calories: 70,
    protein: 2.5,
    carbs: 12,
    fat: 1.5,
    servingSize: "100g",
  },
  {
    name: "Whole wheat bread",
    category: "Carbs - Grains",
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.5,
    servingSize: "100g (2 slices)",
  },
  {
    name: "White bread",
    category: "Carbs - Grains",
    calories: 265,
    protein: 9,
    carbs: 50,
    fat: 3.2,
    servingSize: "100g (2 slices)",
  },
  {
    name: "Sweet potato (cooked)",
    category: "Carbs - Tubers",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "White potato (cooked)",
    category: "Carbs - Tubers",
    calories: 87,
    protein: 1.9,
    carbs: 20,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "Banana",
    category: "Carbs - Fruit",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    servingSize: "1 medium (118g)",
  },
  {
    name: "Apple",
    category: "Carbs - Fruit",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    servingSize: "1 medium (182g)",
  },
  {
    name: "Orange",
    category: "Carbs - Fruit",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    servingSize: "1 medium (131g)",
  },
  {
    name: "Berries (mixed)",
    category: "Carbs - Fruit",
    calories: 32,
    protein: 0.4,
    carbs: 7.5,
    fat: 0.2,
    servingSize: "100g",
  },
  {
    name: "Pasta (cooked, enriched)",
    category: "Carbs - Grains",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    servingSize: "100g",
  },
  {
    name: "Whole wheat pasta (cooked)",
    category: "Carbs - Grains",
    calories: 124,
    protein: 5.3,
    carbs: 26,
    fat: 0.5,
    servingSize: "100g",
  },
  {
    name: "Corn (cooked)",
    category: "Carbs - Vegetable",
    calories: 86,
    protein: 3.3,
    carbs: 19,
    fat: 1.4,
    servingSize: "100g",
  },
  // FATS
  {
    name: "Olive oil",
    category: "Fat - Oil",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    servingSize: "100g",
  },
  {
    name: "Coconut oil",
    category: "Fat - Oil",
    calories: 892,
    protein: 0,
    carbs: 0,
    fat: 100,
    servingSize: "100g",
  },
  {
    name: "Avocado",
    category: "Fat - Whole Food",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    servingSize: "1/2 avocado (100g)",
  },
  {
    name: "Almonds",
    category: "Fat - Nuts",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    servingSize: "100g",
  },
  {
    name: "Walnuts",
    category: "Fat - Nuts",
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    servingSize: "100g",
  },
  {
    name: "Peanut butter",
    category: "Fat - Nuts",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    servingSize: "100g",
  },
  {
    name: "Almond butter",
    category: "Fat - Nuts",
    calories: 614,
    protein: 21,
    carbs: 19,
    fat: 55,
    servingSize: "100g",
  },
  {
    name: "Cashews",
    category: "Fat - Nuts",
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    servingSize: "100g",
  },
  {
    name: "Chia seeds",
    category: "Fat - Seeds",
    calories: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    servingSize: "100g",
  },
  {
    name: "Flax seeds",
    category: "Fat - Seeds",
    calories: 534,
    protein: 18,
    carbs: 29,
    fat: 42,
    servingSize: "100g",
  },
  {
    name: "Cheese (cheddar)",
    category: "Fat - Dairy",
    calories: 402,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    servingSize: "100g",
  },
  {
    name: "Butter",
    category: "Fat - Dairy",
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    servingSize: "100g",
  },
  // VEGETABLES
  {
    name: "Broccoli",
    category: "Vegetable",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    servingSize: "100g",
  },
  {
    name: "Spinach",
    category: "Vegetable",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    servingSize: "100g",
  },
  {
    name: "Kale",
    category: "Vegetable",
    calories: 35,
    protein: 2.9,
    carbs: 5,
    fat: 0.6,
    servingSize: "100g",
  },
  {
    name: "Asparagus",
    category: "Vegetable",
    calories: 20,
    protein: 2.2,
    carbs: 4,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "Bell peppers (mixed)",
    category: "Vegetable",
    calories: 26,
    protein: 0.9,
    carbs: 6,
    fat: 0.2,
    servingSize: "100g",
  },
  {
    name: "Carrots",
    category: "Vegetable",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    servingSize: "100g",
  },
  {
    name: "Cauliflower",
    category: "Vegetable",
    calories: 25,
    protein: 2,
    carbs: 5,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "Green beans",
    category: "Vegetable",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "Mushrooms",
    category: "Vegetable",
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    servingSize: "100g",
  },
  {
    name: "Tomatoes",
    category: "Vegetable",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    servingSize: "100g",
  },
  {
    name: "Lettuce (romaine)",
    category: "Vegetable",
    calories: 17,
    protein: 1.4,
    carbs: 3.3,
    fat: 0.3,
    servingSize: "100g",
  },
  {
    name: "Cucumber",
    category: "Vegetable",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "Zucchini",
    category: "Vegetable",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    servingSize: "100g",
  },
  // LEGUMES
  {
    name: "Black beans (cooked)",
    category: "Protein - Plant",
    calories: 132,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
    servingSize: "100g",
  },
  {
    name: "Kidney beans (cooked)",
    category: "Protein - Plant",
    calories: 127,
    protein: 8.7,
    carbs: 23,
    fat: 0.5,
    servingSize: "100g",
  },
  {
    name: "Chickpeas (cooked)",
    category: "Protein - Plant",
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    servingSize: "100g",
  },
  {
    name: "Lentils (cooked)",
    category: "Protein - Plant",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    servingSize: "100g",
  },
  // BEVERAGES
  {
    name: "Milk (whole)",
    category: "Beverage - Dairy",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    servingSize: "100g",
  },
  {
    name: "Milk (2%)",
    category: "Beverage - Dairy",
    calories: 50,
    protein: 3.3,
    carbs: 4.8,
    fat: 2,
    servingSize: "100g",
  },
  {
    name: "Milk (skim)",
    category: "Beverage - Dairy",
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    servingSize: "100g",
  },
  {
    name: "Orange juice",
    category: "Beverage",
    calories: 45,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    servingSize: "100g",
  },
  {
    name: "Protein shake (whey)",
    category: "Beverage - Supplement",
    calories: 200,
    protein: 30,
    carbs: 5,
    fat: 3,
    servingSize: "1 shake (300ml)",
  },
  // SNACKS
  {
    name: "Dark chocolate (70%)",
    category: "Snack",
    calories: 598,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    servingSize: "100g",
  },
  {
    name: "Popcorn (air-popped)",
    category: "Snack",
    calories: 387,
    protein: 13,
    carbs: 78,
    fat: 5,
    servingSize: "100g",
  },
  {
    name: "Rice cakes",
    category: "Snack",
    calories: 391,
    protein: 8,
    carbs: 80,
    fat: 3,
    servingSize: "100g",
  },
] as const;

async function main() {
  console.log("Starting seed...");

  const existingCount = await prisma.food.count();
  if (existingCount > 0) {
    console.log(`Found ${existingCount} existing foods. Skipping seed.`);
    return;
  }

  for (const food of SEED_FOODS) {
    await prisma.food.create({
      data: {
        name: food.name,
        category: food.category,
        calories: food.calories,
        protein: food.protein,
        carbs: food.carbs,
        fat: food.fat,
        servingSize: food.servingSize,
        isCustom: false,
      },
    });
  }

  console.log(`Seeded ${SEED_FOODS.length} foods`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
